run:
  stages:
    - inference
    - evaluation
    - analysis

inference:
  models:
    - name: "claude-3-7-sonnet-latest"
      include_reasoning: true
      temperature: 1

    - name: "gpt-4o"
      temperature: 1

  datasets:
    - name: "gpqa"
      num_questions: 100
      shuffle: true

  concurrency:
    max_workers: 10

evaluation:
  grader_model: "gpt-4o"
  max_workers: 50
  grade_legibility: true
  grade_correctness: true

analysis:
  plots:
    - legibility_scores_boxplot
    - correctness_assessment
    - legibility_by_correctness