run:
  stages:
  - analysis
analysis:
  baseline_file: runs/20251013_001335_claude-3-7-sonnet-latest_gpqa/evaluation.json
  comparison:
    enabled: true
    runs:
    - runs/20251013_001335_claude-3-7-sonnet-latest_gpqa
    - runs/20251013_002904_gpt-4o_gpqa
    - runs/20251013_035305_R1_gpqa
    plot_types:
    - model_comparison
    - legibility_comparison
    - legibility_by_difficulty_comparison
    - correctness_vs_legibility_scatter_comparison
    - correctness_vs_legibility_scatter_comparison_normalized
  statistics:
  - summary
  plots: []
